In [1]:
import numpy as np 
import pandas as pd

In [4]:
benz = pd.read_csv("E:\mercedes_benz_sales\mercedes_benz_sales_2020_2025.csv")

In [5]:
benz.head(5)

,Model,Year,Region,Color,Fuel Type,Base Price (USD),Horsepower,Sales Volume,Turbo
0,A-Class,2020,Global,Yellow,Diesel,41265,252,1,Yes
1,A-Class,2020,Global,Black,Petrol,51023,249,1,No
2,A-Class,2020,Global,Grey,Petrol,72819,341,1,Yes
3,A-Class,2020,Global,Black,Petrol,62480,385,1,Yes
4,A-Class,2020,Global,White,Petrol,35189,337,1,Yes

In [25]:
benz.columns
benz.dtypes

model               object
year                 int64
region              object
color               object
fuel_type           object
base_price_(usd)     int64
horsepower           int64
sales_volume         int64
turbo               object
dtype: object

In [6]:
benz.describe()

               Year  Base Price (USD)    Horsepower  Sales Volume
count  1.213267e+07      1.213267e+07  1.213267e+07    12132666.0
mean   2.022548e+03      1.042169e+05  3.674594e+02           1.0
std    1.658896e+00      6.783388e+04  1.195446e+02           0.0
min    2.020000e+03      3.500000e+04  1.500000e+02           1.0
25%    2.021000e+03      6.346200e+04  2.750000e+02           1.0
50%    2.023000e+03      8.357200e+04  3.580000e+02           1.0
75%    2.024000e+03      1.199200e+05  4.440000e+02           1.0
max    2.025000e+03      4.112460e+05  8.310000e+02           1.0

In [7]:
benz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12132666 entries, 0 to 12132665
Data columns (total 9 columns):
 #   Column            Dtype
---  ------            -----
 0   Model             object
 1   Year              int64
 2   Region            object
 3   Color             object
 4   Fuel Type         object
 5   Base Price (USD)  int64
 6   Horsepower        int64
 7   Sales Volume      int64
 8   Turbo             object
dtypes: int64(4), object(5)
memory usage: 833.1+ MB

In [12]:
# checking a data whether it has a null value
benz.isnull().sum()

Model               0
Year                0
Region              0
Color               0
Fuel Type           0
Base Price (USD)    0
Horsepower          0
Sales Volume        0
Turbo               0
dtype: int64

In [14]:
# checking a data whether it has a duplicated values
benz.duplicated().sum()

np.int64(3153)

In [18]:
# removing a duplicates form a dataset 
benz = benz.drop_duplicates()

print(benz.duplicated().sum())

0

In [24]:
#Rename columns
benz.columns = (
    benz.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
benz.columns

Index(['model', 'year', 'region', 'color', 'fuel_type', 'base_price_(usd)',
       'horsepower', 'sales_volume', 'turbo'],
      dtype='object')